build:
    dependencies:
        before:
            - sudo rm -rf haxe
            - sudo apt-get update
            - sudo apt-get -y install ocaml ocaml-native-compilers camlp4-extra opam
            -
                command: 'git clone https://github.com/joyent/node.git && cd node && ./configure --prefix=../nodejs sudo make && sudo make install'
                not_if: 'test -e node'
            -
                command: 'sudo git clone --recursive git://github.com/HaxeFoundation/haxe.git && cd haxe && sudo make && sudo make install && cd ../'
                not_if: 'test -e haxe'
            -
                command: 'sudo npm install coffee-script stylus'
                not_if: 'test -e node_modules'
            - export PATH=node_modules/.bin:$PATH
            - which haxe && haxe -v
            - which coffee && coffee -v
            - which stylus && stylus --version
    cache:
        directories:
            - 'haxe'
            - '/usr/bin/haxe'
            - '/usr/bin/haxelib'
            - 'node'
            - 'nodejs'
            - 'node_modules'
    environment:
        php:
            version: 5.5.12
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --exclude-group compile'
                coverage:
                    file: build/logs/clover.xml
                    format: php-clover
tools:
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
    php_analyzer:
        enabled: true
        extensions:
            - php
    sensiolabs_security_checker:
        enabled: true
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
filter:
    excluded_paths:
        - 'tests/*'
    paths: {  }
build_failure_conditions: {  }