build:
    dependencies:
        before:
            - sudo ls -al src/haxe
            - sudo ls -al src/haxe/haxe
            - sudo ls -al src/haxe/libs
            - sudo apt-get update
            - sudo apt-get -y install ocaml ocaml-native-compilers camlp4-extra opam
            -
                command: 'mkdir src'
                not_if: 'test -e src'
            -
                command: 'cd src && git clone https://github.com/joyent/node.git && cd node && sudo ./configure --prefix=./ && sudo make && sudo make install && cd ../../'
                not_if: 'test -e src/node'
            - export PATH=~/build/src/node/bin:$PATH
            -
                command: 'cd src && git clone https://github.com/npm/npm && cd npm && ./configure --prefix=./ && make && make install && cd ../../'
                not_if: 'test -e src/npm'
            - export PATH=~/build/src/npm/bin:$PATH
            -
                command: 'npm install coffee-script stylus'
                not_if: 'test -e node_modules'
            -  export PATH=~/build/node_modules/.bin:$PATH
            -
                command: 'cd src && git clone --recursive git://github.com/HaxeFoundation/haxe.git && cd haxe && sudo make && sudo make install && sudo mkdir bin && sudo cp /usr/bin/haxe bin/ && sudo cp /usr/bin/haxelib bin/ && cd ../../'
                not_if: 'test -e src/haxe'
            - export PATH=~/build/src/haxe/bin:$PATH
            - which coffee && coffee -v
            - which stylus && stylus --version
            - which haxe && haxe
    cache:
        directories:
            - 'src/'
            - 'node_modules/'
    environment:
        php:
            version: 5.5.12
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
                coverage:
                    file: build/logs/clover.xml
                    format: php-clover
tools:
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
    php_analyzer:
        enabled: true
        extensions:
            - php
    sensiolabs_security_checker:
        enabled: true
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
filter:
    excluded_paths:
        - 'tests/*'
    paths: {  }
build_failure_conditions: {  }