build:
    environment:
        php:
            version: 5.5.12
    tests:
        override:
            -
                command: 'phpunit --exclude-group compile'
tools:
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
    php_analyzer:
        enabled: true
        extensions:
            - php
    sensiolabs_security_checker:
        enabled: true
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
filter:
    excluded_paths:
        - 'tests/*'
    paths: {  }
build_failure_conditions: {  }