build:
    environment:
        php:
            version: 5.5.12
    dependencies:
        before:
            - 'sudo apt-get install libzip-dev ocaml git camlp4'
            - 'git clone --recursive https://github.com/HaxeFoundation/haxe.git haxe'
            - 'cd haxe && make clean all && sudo make install'
tools:
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
    php_analyzer:
        enabled: true
        extensions:
            - php
    sensiolabs_security_checker:
        enabled: true
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
filter:
    excluded_paths:
        - 'tests/*'
    paths: {  }
build_failure_conditions: {  }