build:
    container: base/ubuntu/trusty/amd64
    project_setup:
        before:
            - add-apt-repository ppa:ondrej/php5-5.6
            - apt-get update
            - apt-get -y install git ocaml ocaml-native-compilers camlp4-extra opam nodejs npm php5
            -
                command: 'git clone --recursive git://github.com/HaxeFoundation/haxe.git && cd haxe && make && make install && cd ../'
                not_if: 'test -e haxe'
            -
                command: 'npm install -g coffee-script stylus'
            -
                command: 'curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer'
                not_if: 'which composer'
            - which composer
            - which haxe && haxe -v
            - which coffee && coffee -v
            - which stylus && stylus --version
    cache:
        directories:
            - 'haxe'
            - '/usr/bin/haxe'
            - '/usr/bin/haxelib'
            - '/usr/local/bin/composer'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --exclude-group compile'
                coverage:
                    file: build/logs/clover.xml
                    format: php-clover
tools:
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
    php_analyzer:
        enabled: true
        extensions:
            - php
    sensiolabs_security_checker:
        enabled: true
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
filter:
    excluded_paths:
        - 'tests/*'
    paths: {  }
build_failure_conditions: {  }